sensor:
  - platform: filter
    name: "stat_h6_power"
    unique_id: stat_h6_power
    entity_id: sensor.stat_h6_power_raw
    filters:
      - filter: range
        lower_bound: -950
        upper_bound: 5000

  - platform: filter
    name: "stat_h6_pv_power"
    unique_id: stat_h6_pv_power
    entity_id: sensor.stat_h6_pv_power_raw
    filters:
      - filter: range
        lower_bound: 0
        upper_bound: 950

template:
  - sensor:
      - name: "stat_h6_power_raw"
        state: "{{ states('number.s4lo02_h6power') }}"
        availability: >
          {{ states('number.s4lo02_h6power') not in [none, 'unknown', 'unavailable', 'none', ''] }}
        unit_of_measurement: W
        device_class: power
        state_class: measurement
  - sensor:
      - name: "stat_h6_pv_power_raw"
        state: "{{ states('number.s4lo02_h6pvpower') }}"
        availability: >
          {{ states('number.s4lo02_h6pvpower') not in [none, 'unknown', 'unavailable', 'none', ''] }}
        unit_of_measurement: W
        device_class: power
        state_class: measurement

  - sensor:
    - name: "stat_h6_energy"
      unique_id: stat_h6_energy
      state: >
        {{ (states('number.s4lo02_h6energy') | float / 1000) | round(2) }}
      availability: >
        {{ states('number.s4lo02_h6energy') not in ['unknown', 'unavailable', 'none', ''] }}
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing

  - sensor:
    - name: "stat_h6_pv_energy"
      unique_id: stat_h6_pv_energy
      state: >
        {{ (states('number.s4lo02_h6pvenergy') | float / 1000) | round(2) }}
      availability: >
        {{ states('number.s4lo02_h6pvenergy') not in ['unknown', 'unavailable', 'none', ''] }}
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing

  - sensor:
    - name: "stat_h6_energy2"
      unique_id: stat_h6_energy2
      state: >
        {% set val = (states('number.s4lo02_h6energy') | float(none) / 1000) | round(2) if states('number.s4lo02_h6energy') not in ['unknown', 'unavailable', 'none', ''] else none %}
        {% set prev = states('sensor.stat_h6_energy2') | float(0) %}
        {% set max_increase_percent = 1.10 %}
        
        {% if val is none %}
          {{ prev }}
        {% elif prev == 0 %}
          {{ val }}
        {% elif val >= prev and val <= (prev * max_increase_percent) %}
          {{ val }}
        {% else %}
          {{ prev }}
        {% endif %}
      availability: >
        {{ states('number.s4lo02_h6energy') not in ['unknown', 'unavailable', 'none', ''] }}
      attributes:
        status: >
          {% set val = (states('number.s4lo02_h6energy') | float(none) / 1000) | round(2) if states('number.s4lo02_h6energy') not in ['unknown', 'unavailable', 'none', ''] else none %}
          {% set prev = states('sensor.stat_h6_energy2') | float(0) %}
          {% set max_increase_percent = 1.10 %}
          
          {% if val is none %}
            unavailable
          {% elif prev == 0 %}
            initialized
          {% elif val >= prev and val <= (prev * max_increase_percent) %}
            updated
          {% else %}
            rejected
          {% endif %}
        raw_value: "{{ states('number.s4lo02_h6energy') }}"
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing
      
  - sensor:
    - name: "stat_h6_pv_energy2"
      unique_id: stat_h6_pv_energy2
      state: >
        {% set val = (states('number.s4lo02_h6pvenergy') | float(none) / 1000) | round(2) if states('number.s4lo02_h6pvenergy') not in ['unknown', 'unavailable', 'none', ''] else none %}
        {% set prev = states('sensor.stat_h6_pv_energy2') | float(0) %}
        {% set max_increase_percent = 1.10 %}
        
        {% if val is none %}
          {{ prev }}
        {% elif prev == 0 %}
          {{ val }}
        {% elif val >= prev and val <= (prev * max_increase_percent) %}
          {{ val }}
        {% else %}
          {{ prev }}
        {% endif %}
      availability: >
        {{ states('number.s4lo02_h6energy') not in ['unknown', 'unavailable', 'none', ''] }}
      attributes:
        status: >
          {% set val = (states('number.s4lo02_h6pvenergy') | float(none) / 1000) | round(2) if states('number.s4lo02_h6pvenergy') not in ['unknown', 'unavailable', 'none', ''] else none %}
          {% set prev = states('sensor.stat_h6_pv_energy2') | float(0) %}
          {% set max_increase_percent = 1.10 %}
          
          {% if val is none %}
            unavailable
          {% elif prev == 0 %}
            initialized
          {% elif val >= prev and val <= (prev * max_increase_percent) %}
            updated
          {% else %}
            rejected
          {% endif %}
        raw_value: "{{ states('number.s4lo02_h6pvenergy') }}"
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing
      
  - sensor:
    - name: "stat_h6_pv_power_err"
      unique_id: stat_h6_pv_power_err
      state: >
        {% set val = states('number.s4lo02_h6pvpower') | float(none) %}
        {% set min_val = 0 %}
        {% set max_val = 950 %}
        {% if val is not none and val < min_val and val > max_val %}
          {{ val | round(0) }}
        {% endif %}
      availability: >
        {{ states('number.s4lo02_h6pvpower') not in ['unknown', 'unavailable', 'none', ''] }}
      unit_of_measurement: W
      device_class: power
      state_class: measurement      

  # filtered values to get around bad lora data
  - sensor:
    - name: "stat_h6_energy_filtered"
      unique_id: stat_h6_energy_filtered
      state: >
        {% set val = states('sensor.stat_h6_energy') | float(none) %}
        {% set prev = states('sensor.stat_h6_energy_filtered') | float(0) %}
        {% set elapsed_hours = (as_timestamp(now()) - as_timestamp(states.sensor.stat_h6_energy_filtered.last_changed)) / 3600 %}
        {% set first_hour_kwh = 5.0 %}
        {% set additional_hour_kwh = 1.0 %}
        
        {% if elapsed_hours <= 1 %}
          {% set max_allowed = prev + (first_hour_kwh * elapsed_hours) %}
        {% else %}
          {% set max_allowed = prev + first_hour_kwh + (additional_hour_kwh * (elapsed_hours - 1)) %}
        {% endif %}

        {% if val is not none %}
          {% if prev == 0 %}
            {{ val }}
          {% else %}
            {% if val <= max_allowed %}
              {{ val }}
            {% else %}
              {{ prev }}
            {% endif %}
          {% endif %}
        {% else %}
          {{ prev }}
        {% endif %}
      availability: >
        {{ states('sensor.stat_h6_energy') not in ['unknown', 'unavailable', 'none', ''] }}
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing
      
  - sensor:
    - name: "stat_h6_pv_energy_filtered"
      unique_id: stat_h6_pv_energy_filtered
      state: >
        {% set val = states('sensor.stat_h6_pv_energy') | float(none) %}
        {% set prev = states('sensor.stat_h6_pv_energy_filtered') | float(0) %}
        {% set elapsed_hours = (as_timestamp(now()) - as_timestamp(states.sensor.stat_h6_pv_energy_filtered.last_changed)) / 3600 %}
        {% set max_kwh_per_hour = 0.95 %}
        {% set max_allowed = prev + (max_kwh_per_hour * elapsed_hours) %}

        {% if val is not none %}
          {% if prev == 0 %}
            {{ val }}
          {% else %}
            {% if val <= max_allowed %}
              {{ val }}
            {% else %}
              {{ prev }}
            {% endif %}
          {% endif %}
        {% else %}
          {{ prev }}
        {% endif %}
      availability: >
        {{ states('sensor.stat_h6_pv_energy') not in ['unknown', 'unavailable', 'none', ''] }}
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing
